vim.keymap.set("n", "<leader>wv", ":vsplit<CR>", {})
vim.keymap.set("n", "<leader>ws", ":split<CR>", {})
vim.keymap.set("n", "<leader>wo", "<C-w>o", {})
vim.keymap.set("n", "<leader>wj", "<C-w>j", {})
vim.keymap.set("n", "<leader>wk", "<C-w>k", {})
vim.keymap.set("n", "<leader>wh", "<C-w>h", {})
vim.keymap.set("n", "<leader>wl", "<C-w>l", {})

vim.keymap.set("n", "<leader>bn", ":bnext<CR>", {})
vim.keymap.set("n", "<leader>bp", ":bprev<CR>", {})
vim.keymap.set("n", "<leader>bd", ":bdelete<CR>", {})
vim.keymap.set("n", "<leader>bD", ":bdelete!<CR>", {})
vim.keymap.set("n", "<leader>bb", ":Pick buffers<CR>", {})

vim.keymap.set("n", "<leader>y", ":Yazi<CR>", {})

vim.keymap.set("n", "<leader>ff", ":Pick files<CR>", {})
vim.keymap.set("n", "<leader>fs", ":Pick lsp scope='document_symbol'<CR>", {})
vim.keymap.set("n", "<leader>fx", ":Pick diagnostic scope='current'<CR>", {})
vim.keymap.set("n", "<leader>fm", ":Pick marks<CR>", {})
vim.keymap.set("n", "<leader>fp", ":e " .. vim.fn.stdpath('config') .. "<CR>", {})
vim.keymap.set("n", "<leader>/", ":Pick grep_live<CR>", {})

vim.keymap.set("n", "<leader>cf", ":lua require('conform').format()<CR>", {})
vim.keymap.set("n", "<leader>cr", ":lua vim.lsp.buf.rename()<CR>", {})
vim.keymap.set("n", "<leader>ca", ":lua vim.lsp.buf.code_action()<CR>", {})
vim.keymap.set("n", "<leader>ci", ":lua vim.lsp.buf.implementation()<CR>", {})
vim.keymap.set("n", "<leader>cs", ":lua vim.lsp.buf.references()<CR>", {})
vim.keymap.set("n", "<C-k>", ":lua vim.diagnostic.open_float()<CR>", {})
