vim.opt.number = true;
vim.opt.relativenumber = true;
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.expandtab = true
vim.opt.termguicolors = true
vim.opt.completeopt = { "menuone", "noinsert", "noselect" }
vim.opt.signcolumn = "yes:1"
vim.g.mapleader = " "
vim.g.localmapleader = ","
